"""Standalone project code generator (no AgentForge runtime dependency)."""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

from agentforge.ir.models import WorkflowIR
from agentforge.schema import NodeType


@dataclass
class GeneratedProject:
    path: Path
    name: str
    files: list[str]

    def __str__(self) -> str:
        return f"GeneratedProject(name={self.name!r}, path={self.path})"


class ProjectGenerator:
    def __init__(self, template_root: Path | None = None) -> None:
        self.template_root = template_root or Path(__file__).resolve().parents[2] / "templates" / "generated-project"
        self.env = Environment(
            loader=FileSystemLoader(str(self.template_root)),
            autoescape=select_autoescape(enabled_extensions=()),
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def generate(
        self,
        ir: WorkflowIR,
        *,
        output_dir: str | Path | None = None,
        runtime: str = "langgraph",
    ) -> GeneratedProject:
        out = Path(output_dir or f"./generated/{ir.name}")
        if out.exists():
            shutil.rmtree(out)
        out.mkdir(parents=True, exist_ok=True)

        ctx = self._context(ir, runtime=runtime)
        written: list[str] = []

        mapping = {
            "README.md.j2": "README.md",
            "pyproject.toml.j2": "pyproject.toml",
            "Dockerfile.j2": "Dockerfile",
            "docker-compose.yml.j2": "docker-compose.yml",
            ".env.example.j2": ".env.example",
            "Makefile.j2": "Makefile",
            "ARCHITECTURE.md.j2": "docs/ARCHITECTURE.md",
            "WORKFLOW.md.j2": "docs/WORKFLOW.md",
            "AGENTS.md.j2": "docs/AGENTS.md",
            "TOOLS.md.j2": "docs/TOOLS.md",
            "SECURITY.md.j2": "docs/SECURITY.md",
            "EVALUATION.md.j2": "docs/EVALUATION.md",
            "OPERATIONS.md.j2": "docs/OPERATIONS.md",
            "DEPLOYMENT.md.j2": "docs/DEPLOYMENT.md",
            "workflow.mmd.j2": "diagrams/workflow.mmd",
            "ci.yml.j2": ".github/workflows/ci.yml",
            "main.py.j2": "src/workflow_app/main.py",
            "graph.py.j2": "src/workflow_app/graph.py",
            "agents.py.j2": "src/workflow_app/agents.py",
            "tools.py.j2": "src/workflow_app/tools.py",
            "config.py.j2": "src/workflow_app/config.py",
            "state.py.j2": "src/workflow_app/state.py",
            "__init__.py.j2": "src/workflow_app/__init__.py",
            "test_workflow.py.j2": "tests/test_workflow.py",
            "workflow.json.j2": "workflow.json",
        }

        for tmpl, dest in mapping.items():
            target = out / dest
            target.parent.mkdir(parents=True, exist_ok=True)
            if (self.template_root / tmpl).exists():
                content = self.env.get_template(tmpl).render(**ctx)
            else:
                content = self._fallback(tmpl, ctx)
            target.write_text(content, encoding="utf-8")
            written.append(dest)

        # Always write IR snapshot
        (out / "workflow_ir.json").write_text(ir.model_dump_json(indent=2), encoding="utf-8")
        written.append("workflow_ir.json")
        return GeneratedProject(path=out.resolve(), name=ir.name, files=written)

    def _context(self, ir: WorkflowIR, *, runtime: str) -> dict[str, Any]:
        return {
            "name": ir.name,
            "description": ir.description or ir.name,
            "version": ir.version,
            "pattern": ir.pattern.value,
            "runtime": runtime,
            "agents": list(ir.agents.values()),
            "tools": list(ir.tools.values()),
            "nodes": ir.nodes,
            "edges": ir.edges,
            "policies": ir.policies,
            "evaluation": ir.evaluation,
            "mermaid": ir.to_mermaid(),
            "agent_ids": list(ir.agents.keys()),
            "node_ids": [n.id for n in ir.nodes],
            "executable_nodes": [
                n for n in ir.nodes if n.type not in {NodeType.START, NodeType.END}
            ],
            "state_schema": ir.state_schema,
            "ir_json": ir.model_dump(),
        }

    def _fallback(self, tmpl: str, ctx: dict[str, Any]) -> str:
        name = ctx["name"]
        if tmpl == "README.md.j2":
            return (
                f"# {name}\n\n{ctx['description']}\n\n"
                f"Generated by AgentForge. Pattern: `{ctx['pattern']}`.\n\n"
                "## Run\n\n```bash\npip install -e .\npython -m workflow_app.main\npytest\n```\n"
            )
        if tmpl == "pyproject.toml.j2":
            return f"""[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{name.replace('_', '-')}"
version = "{ctx['version']}"
description = "{ctx['description'].replace('"', "'")}"
requires-python = ">=3.11"
dependencies = ["langgraph>=0.2", "langchain-core>=0.3", "pydantic>=2.7", "httpx>=0.27"]

[project.optional-dependencies]
dev = ["pytest>=8.2"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
"""
        if tmpl == "main.py.j2":
            return '''"""CLI entrypoint for the generated workflow."""
from __future__ import annotations

import json
import os
import sys

from workflow_app.graph import build_graph, run_workflow


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    query = " ".join(argv) if argv else os.environ.get("WORKFLOW_INPUT", "hello")
    result = run_workflow({"input": query, "auto_approve": True})
    print(json.dumps(result, indent=2, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''
        if tmpl == "graph.py.j2":
            return self._graph_module(ctx)
        if tmpl == "agents.py.j2":
            return self._agents_module(ctx)
        if tmpl == "tools.py.j2":
            return self._tools_module(ctx)
        if tmpl == "config.py.j2":
            return '''"""Provider-neutral config via environment variables only."""
from __future__ import annotations

import os


def llm_settings() -> dict:
    return {
        "provider": os.environ.get("AGENTFORGE_LLM_PROVIDER", "openai"),
        "model": os.environ.get("AGENTFORGE_LLM_MODEL", "gpt-4o-mini"),
        "api_key": os.environ.get("AGENTFORGE_LLM_API_KEY", ""),
        "base_url": os.environ.get("AGENTFORGE_LLM_BASE_URL", ""),
        "mock": os.environ.get("AGENTFORGE_LLM_MOCK", "1") == "1"
        or not os.environ.get("AGENTFORGE_LLM_API_KEY"),
    }
'''
        if tmpl == "state.py.j2":
            return '''"""Workflow state schema."""
from __future__ import annotations

import operator
from typing import Annotated, Any, TypedDict


class State(TypedDict, total=False):
    input: str
    output: str
    messages: Annotated[list[dict[str, Any]], operator.add]
    route: str
    loop_count: int
    node_outputs: dict[str, Any]
    approved: bool
    scores: dict[str, float]
    meta: dict[str, Any]
'''
        if tmpl == "__init__.py.j2":
            return f'"""Generated workflow package for {name}."""\n__version__ = "{ctx["version"]}"\n'
        if tmpl == "test_workflow.py.j2":
            return '''from workflow_app.graph import run_workflow


def test_run_completes():
    result = run_workflow({"input": "test", "auto_approve": True, "route": "done"})
    assert "output" in result
    assert result["output"]
'''
        if tmpl.endswith(".md.j2"):
            title = tmpl.replace(".md.j2", "").replace("_", " ")
            return f"# {title}\n\n{ctx['description']}\n\nPattern: `{ctx['pattern']}`\nRuntime: `{ctx['runtime']}`\n"
        if tmpl == "workflow.mmd.j2":
            return ctx["mermaid"] + "\n"
        if tmpl == "Dockerfile.j2":
            return """FROM python:3.12-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -e .
CMD [\"python\", \"-m\", \"workflow_app.main\"]
"""
        if tmpl == "docker-compose.yml.j2":
            return """services:
  workflow:
    build: .
    environment:
      AGENTFORGE_LLM_MOCK: \"1\"
    command: [\"python\", \"-m\", \"workflow_app.main\", \"hello\"]
"""
        if tmpl == ".env.example.j2":
            return """AGENTFORGE_LLM_PROVIDER=openai
AGENTFORGE_LLM_MODEL=gpt-4o-mini
AGENTFORGE_LLM_API_KEY=
AGENTFORGE_LLM_BASE_URL=
AGENTFORGE_LLM_MOCK=1
"""
        if tmpl == "Makefile.j2":
            return """.PHONY: run test
run:
\tpython -m workflow_app.main
test:
\tpytest -q
"""
        if tmpl == "ci.yml.j2":
            return """name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: \"3.12\"
      - run: pip install -e \".[dev]\"
      - run: pytest -q
"""
        if tmpl == "workflow.json.j2":
            return json.dumps(ctx["ir_json"], indent=2)
        return f"# generated placeholder for {tmpl}\n"

    def _agents_module(self, ctx: dict[str, Any]) -> str:
        lines = [
            '"""Agent definitions (standalone)."""',
            "from __future__ import annotations",
            "",
            "from workflow_app.config import llm_settings",
            "",
            "AGENTS = {",
        ]
        for a in ctx["agents"]:
            lines.append(
                f'    "{a.id}": {{"role": {a.role!r}, "system_prompt": {a.system_prompt!r}, "tools": {list(a.tools)!r}}},'
            )
        if not ctx["agents"]:
            lines.append(
                '    "agent": {"role": "assistant", "system_prompt": "You are helpful.", "tools": []},'
            )
        lines += [
            "}",
            "",
            "",
            "def run_agent(agent_id: str, user_input: str) -> str:",
            "    agent = AGENTS.get(agent_id) or {\"system_prompt\": \"You are helpful.\"}",
            "    settings = llm_settings()",
            "    prompt = agent[\"system_prompt\"]",
            "    if settings[\"mock\"]:",
            "        snippet = (user_input or \"\").strip().replace(\"\\n\", \" \")",
            "        if len(snippet) > 120:",
            "            snippet = snippet[:117] + \"...\"",
            '        return f\"[{agent_id}] {prompt.split(\".\")[0].strip()}: {snippet or \"OK\"}\"',
            "    # Non-mock: integrate your provider SDK using env-only credentials.",
            '    return f\"[{agent_id}] {user_input}\"',
            "",
        ]
        return "\n".join(lines)

    def _tools_module(self, ctx: dict[str, Any]) -> str:
        return '''"""Tools with explicit permissions (standalone)."""
from __future__ import annotations

from typing import Any


def echo(state: dict[str, Any]) -> str:
    return str(state.get("input", ""))


def upper(state: dict[str, Any]) -> str:
    return str(state.get("input", "")).upper()


TOOLS = {
    "echo": echo,
    "upper": upper,
}


def invoke_tool(tool_id: str, state: dict[str, Any]) -> Any:
    if tool_id not in TOOLS:
        raise KeyError(f"Unknown or ungranted tool: {tool_id}")
    return TOOLS[tool_id](state)
'''

    def _graph_module(self, ctx: dict[str, Any]) -> str:
        # Emit a concrete LangGraph module for the IR
        agent_nodes = [n for n in ctx["nodes"] if n.type == NodeType.AGENT]
        lines = [
            '"""Compiled workflow graph (standalone LangGraph)."""',
            "from __future__ import annotations",
            "",
            "from typing import Any",
            "",
            "from langgraph.checkpoint.memory import MemorySaver",
            "from langgraph.graph import END, START, StateGraph",
            "",
            "from workflow_app.agents import run_agent",
            "from workflow_app.state import State",
            "from workflow_app.tools import invoke_tool",
            "",
            "",
            "def build_graph():",
            "    g = StateGraph(State)",
        ]
        for n in ctx["nodes"]:
            if n.type in {NodeType.START, NodeType.END}:
                continue
            if n.type == NodeType.AGENT:
                aid = n.agent_id or n.id
                lines += [
                    f"    def node_{n.id}(state: State) -> dict[str, Any]:",
                    f'        text = run_agent({aid!r}, str(state.get("input", "")))',
                    f'        outs = dict(state.get("node_outputs") or {{}})',
                    f"        outs[{n.id!r}] = text",
                    '        return {"output": text, "messages": [{"role": "assistant", "content": text}], "node_outputs": outs}',
                    f"    g.add_node({n.id!r}, node_{n.id})",
                ]
            elif n.type == NodeType.TOOL:
                tid = n.tool_id or n.id
                lines += [
                    f"    def node_{n.id}(state: State) -> dict[str, Any]:",
                    f"        result = invoke_tool({tid!r}, dict(state))",
                    '        return {"output": str(result)}',
                    f"    g.add_node({n.id!r}, node_{n.id})",
                ]
            elif n.type == NodeType.JOIN:
                lines += [
                    f"    def node_{n.id}(state: State) -> dict[str, Any]:",
                    '        outs = state.get("node_outputs") or {}',
                    '        return {"output": " | ".join(str(v) for v in outs.values())}',
                    f"    g.add_node({n.id!r}, node_{n.id})",
                ]
            elif n.type == NodeType.HUMAN_APPROVAL:
                lines += [
                    f"    def node_{n.id}(state: State) -> dict[str, Any]:",
                    '        if state.get("meta", {}).get("auto_approve", True) or state.get("approved"):',
                    '            return {"approved": True}',
                    '        return {"approved": False, "output": state.get("output")}',
                    f"    g.add_node({n.id!r}, node_{n.id})",
                ]
            elif n.type == NodeType.EVALUATOR:
                lines += [
                    f"    def node_{n.id}(state: State) -> dict[str, Any]:",
                    '        output = str(state.get("output", ""))',
                    "        score = 0.9 if output else 0.2",
                    '        return {"scores": {"correctness": score, "safety": 0.95}}',
                    f"    g.add_node({n.id!r}, node_{n.id})",
                ]
            else:
                lines += [
                    f"    def node_{n.id}(state: State) -> dict[str, Any]:",
                    "        return {}",
                    f"    g.add_node({n.id!r}, node_{n.id})",
                ]

        # Edges
        for e in ctx["edges"]:
            src, tgt = e.source, e.target
            src_is_start = any(n.id == src and n.type == NodeType.START for n in ctx["nodes"])
            tgt_is_end = any(n.id == tgt and n.type == NodeType.END for n in ctx["nodes"])
            if src_is_start:
                lines.append(f"    g.add_edge(START, {tgt!r})" if not tgt_is_end else "    g.add_edge(START, END)")
            elif tgt_is_end:
                lines.append(f"    g.add_edge({src!r}, END)")
            else:
                lines.append(f"    g.add_edge({src!r}, {tgt!r})")

        lines += [
            "    return g.compile(checkpointer=MemorySaver())",
            "",
            "",
            "def run_workflow(payload: dict[str, Any] | None = None) -> dict[str, Any]:",
            "    payload = payload or {}",
            "    graph = build_graph()",
            '    thread_id = str(payload.get("thread_id") or "local-1")',
            '    config = {"configurable": {"thread_id": thread_id}}',
            "    state = {",
            '        "input": str(payload.get("input", "")),',
            '        "output": "",',
            '        "messages": [],',
            '        "node_outputs": {},',
            '        "route": str(payload.get("route", "done")),',
            '        "loop_count": 0,',
            '        "approved": False,',
            '        "meta": {"auto_approve": payload.get("auto_approve", True)},',
            "    }",
            "    for k, v in payload.items():",
            "        if k not in state:",
            "            state[k] = v",
            "    result = graph.invoke(state, config)",
            "    return {",
            '        "output": result.get("output"),',
            '        "scores": result.get("scores", {}),',
            '        "node_outputs": result.get("node_outputs", {}),',
            "    }",
            "",
        ]
        # Ensure at least one agent if graph empty of agents
        if not agent_nodes:
            pass
        return "\n".join(lines)
